import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { CalendarDays, ClipboardList, FileText, BriefcaseBusiness, Receipt, Users, ArrowRight } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { DashboardShell, useDashboardAccess, Stat, Panel, Empty, money, day } from "@/components/dashboard/DashboardShell";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/admin")({ head: () => ({ meta: [{ title: "Business Dashboard | Zentric Electrical Services" }, { name: "description", content: "Manage Zentric customer requests, bookings, jobs, quotes and invoices." }, { property: "og:title", content: "Business Dashboard | Zentric" }, { property: "og:description", content: "Zentric business operations." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: AdminDashboard });

function AdminDashboard() {
  const access = useDashboardAccess("admin");
  const data = useQuery({ queryKey: ["admin-overview"], enabled: !!access.data?.allowed, queryFn: async () => {
    const results = await Promise.all([
      supabase.from("enquiries").select("id,reference,full_name,status,created_at").order("created_at", { ascending: false }),
      supabase.from("bookings").select("id,reference,full_name,status,scheduled_date,scheduled_time").order("scheduled_date", { ascending: true }),
      supabase.from("quotes").select("id,reference,title,status,total,created_at").order("created_at", { ascending: false }),
      supabase.from("jobs").select("id,reference,title,status,start_date").order("start_date", { ascending: false }),
      supabase.from("invoices").select("id,reference,status,total,amount_paid").order("created_at", { ascending: false }),
      supabase.from("customers").select("id,customer_number,full_name,created_at").order("created_at", { ascending: false }),
      supabase.from("payments").select("id,reference,amount,status,created_at").order("created_at", { ascending: false }),
      supabase.from("reviews").select("id,author_name,rating,status,created_at").order("created_at", { ascending: false }),
      supabase.from("documents").select("id,title,doc_type,created_at").order("created_at", { ascending: false }),
    ]);
    const failure = results.find((r) => r.error); if (failure?.error) throw failure.error;
    return results.map((r) => r.data) as [NonNullable<typeof results[0]["data"]>, NonNullable<typeof results[1]["data"]>, NonNullable<typeof results[2]["data"]>, NonNullable<typeof results[3]["data"]>, NonNullable<typeof results[4]["data"]>, NonNullable<typeof results[5]["data"]>, NonNullable<typeof results[6]["data"]>, NonNullable<typeof results[7]["data"]>, NonNullable<typeof results[8]["data"]>];
  } });
  const [enquiries, bookings, quotes, jobs, invoices, customers, payments, reviews, documents] = data.data ?? [[], [], [], [], [], [], [], [], []];
  const section = <T extends { id: string }>(rows: T[], label: (row: T) => string, detail: (row: T) => string, empty: string) => rows.length ? <div className="divide-y divide-border rounded-md border border-border bg-card">{rows.map((r) => <div key={r.id} className="flex flex-wrap justify-between gap-2 px-4 py-3 text-sm"><strong>{label(r)}</strong><span className="text-muted-foreground">{detail(r)}</span></div>)}</div> : <Empty text={empty} />;
  const today = new Date().toISOString().slice(0, 10);
  return <DashboardShell area="admin" active="overview"><div className="mb-8"><p className="eyebrow">Operations</p><h1 className="mt-1 text-3xl font-bold">Dashboard</h1><p className="mt-2 text-sm text-muted-foreground">Zentric Electrical Services</p></div>
    {data.isLoading ? <p>Loading business activity…</p> : data.isError ? <p className="text-destructive">Business activity could not be loaded. Please refresh the page.</p> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Today’s jobs" value={jobs.filter((j) => j.start_date === today).length} icon={CalendarDays} /><Stat label="Pending requests" value={enquiries.filter((e) => e.status === "NEW").length} icon={ClipboardList} tone="gold" /><Stat label="Pending quotes" value={quotes.filter((q) => ["DRAFT", "SENT"].includes(q.status)).length} icon={FileText} /><Stat label="Active jobs" value={jobs.filter((j) => !["COMPLETED", "CLOSED", "CANCELLED"].includes(j.status)).length} icon={BriefcaseBusiness} /><Stat label="Completed jobs" value={jobs.filter((j) => ["COMPLETED", "CLOSED"].includes(j.status)).length} icon={BriefcaseBusiness} tone="gold" /></div>
    <div className="mt-4 grid gap-4 sm:grid-cols-3"><Stat label="Confirmed revenue" value={money(payments.filter((p) => p.status === "CONFIRMED").reduce((n, p) => n + Number(p.amount), 0))} icon={Receipt} tone="gold" /><Stat label="Outstanding invoices" value={money(invoices.reduce((n, i) => n + (i.status === "PAID" ? 0 : Math.max(0, Number(i.total) - Number(i.amount_paid))), 0))} icon={Receipt} /><Stat label="Customers" value={customers.length} icon={Users} /></div>
    <div className="mt-8 grid gap-x-8 lg:grid-cols-2"><Panel id="enquiries" title="Recent Enquiries">{section(enquiries, (r) => `${r.reference} · ${r.full_name}`, (r) => `${r.status} · ${day(r.created_at)}`, "No enquiries yet.")}</Panel><Panel id="bookings" title="Upcoming Site Visits">{section(bookings.filter((b) => b.scheduled_date >= today && !["CANCELLED", "COMPLETED"].includes(b.status)), (r) => `${r.reference} · ${r.full_name}`, (r) => `${day(r.scheduled_date)} · ${r.scheduled_time}`, "No upcoming visits.")}</Panel><Panel id="customers" title="Recent Customers">{section(customers.slice(0, 8), (r) => r.full_name, (r) => `${r.customer_number} · ${day(r.created_at)}`, "No customers yet.")}</Panel><Panel id="quotes" title="Quotations">{section(quotes, (r) => `${r.reference} · ${r.title}`, (r) => `${r.status} · ${money(r.total)}`, "No quotations issued.")}</Panel><Panel id="jobs" title="Jobs">{section(jobs, (r) => `${r.reference} · ${r.title}`, (r) => r.status.replaceAll("_", " "), "No jobs yet.")}</Panel><Panel id="invoices" title="Invoices">{section(invoices, (r) => r.reference, (r) => `${r.status} · ${money(r.total)}`, "No invoices issued.")}</Panel><Panel id="payments" title="Recent Payments">{section(payments, (r) => r.reference, (r) => `${r.status} · ${money(r.amount)}`, "No payments recorded.")}</Panel><Panel id="reviews" title="Recent Reviews">{section(reviews, (r) => r.author_name, (r) => `${r.rating}/5 · ${r.status}`, "No reviews yet.")}</Panel><Panel id="documents" title="Document Center">{section(documents, (r) => r.title, (r) => `${r.doc_type} · ${day(r.created_at)}`, "No documents generated yet.")}</Panel><Panel id="notifications" title="Notifications"><Empty text="New requests and bookings appear in the lists above." /></Panel><Panel id="technicians" title="Technicians"><Empty text="Technician management is not available yet." /></Panel><Panel id="projects" title="Projects"><Button asChild variant="outline"><Link to="/projects">View published projects <ArrowRight /></Link></Button></Panel><Panel id="services" title="Services"><Button asChild variant="outline"><Link to="/services">View services <ArrowRight /></Link></Button></Panel><Panel id="content" title="Website Content"><Empty text="Website editing is not available yet." /></Panel><Panel id="settings" title="Settings"><Empty text="Business settings are not editable here yet." /></Panel></div></>}
  </DashboardShell>;
}
