import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { CalendarDays, BriefcaseBusiness, FileText, ClipboardList, Receipt, CreditCard, FolderOpen, Star, UserRound, ArrowRight } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { DashboardShell, useDashboardAccess, Stat, Panel, Empty, money, day } from "@/components/dashboard/DashboardShell";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/dashboard")({ head: () => ({ meta: [{ title: "My Dashboard | Zentric Electrical Services" }, { name: "description", content: "View your Zentric requests, site visits, quotations, jobs and documents." }, { property: "og:title", content: "My Dashboard | Zentric" }, { property: "og:description", content: "Your electrical service account and records." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: CustomerDashboard });

function CustomerDashboard() {
  const access = useDashboardAccess("customer");
  const data = useQuery({ queryKey: ["customer-dashboard", access.data?.user?.id], enabled: !!access.data?.allowed, queryFn: async () => {
    const queries = await Promise.all([
      supabase.from("enquiries").select("id,reference,status,created_at,description").order("created_at", { ascending: false }),
      supabase.from("bookings").select("id,reference,status,scheduled_date,scheduled_time").order("scheduled_date", { ascending: false }),
      supabase.from("quotes").select("id,reference,title,status,total,created_at").order("created_at", { ascending: false }),
      supabase.from("jobs").select("id,reference,title,status,created_at").order("created_at", { ascending: false }),
      supabase.from("invoices").select("id,reference,status,total,amount_paid,issue_date").order("issue_date", { ascending: false }),
      supabase.from("payments").select("id,reference,status,amount,created_at").order("created_at", { ascending: false }),
      supabase.from("receipts").select("id,reference,amount,issued_at").order("issued_at", { ascending: false }),
      supabase.from("documents").select("id,title,doc_type,created_at,file_url").order("created_at", { ascending: false }),
      supabase.from("reviews").select("id,rating,status,created_at").eq("customer_id", (await supabase.from("customers").select("id").eq("profile_id", access.data?.user?.id ?? "").maybeSingle()).data?.id ?? "00000000-0000-0000-0000-000000000000").order("created_at", { ascending: false }),
      supabase.from("profiles").select("full_name,email,phone,whatsapp").eq("id", access.data?.user?.id ?? "").maybeSingle(),
    ]);
    const failure = queries.find((q) => q.error);
    if (failure?.error) throw failure.error;
    return queries.map((q) => q.data) as [NonNullable<typeof queries[0]["data"]>, NonNullable<typeof queries[1]["data"]>, NonNullable<typeof queries[2]["data"]>, NonNullable<typeof queries[3]["data"]>, NonNullable<typeof queries[4]["data"]>, NonNullable<typeof queries[5]["data"]>, NonNullable<typeof queries[6]["data"]>, NonNullable<typeof queries[7]["data"]>, NonNullable<typeof queries[8]["data"]>, typeof queries[9]["data"]];
  } });
  const [requests, visits, quotes, jobs, invoices, payments, receipts, documents, reviews, profile] = data.data ?? [[], [], [], [], [], [], [], [], [], null];
  const list = (rows: Array<{ id: string; reference?: string; title?: string; status?: string; created_at?: string; scheduled_date?: string }>, text: string) => rows.length ? <div className="divide-y divide-border rounded-md border border-border bg-card">{rows.map((row) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-2 px-4 py-3 text-sm"><div><strong>{row.reference ?? row.title}</strong>{row.title && row.reference ? <span className="ml-2 text-muted-foreground">{row.title}</span> : null}</div><span className="text-muted-foreground">{row.status?.replaceAll("_", " ") ?? ""} {row.created_at || row.scheduled_date ? `· ${day(row.created_at ?? row.scheduled_date ?? "")}` : ""}</span></div>)}</div> : <Empty text={text} />;
  return <DashboardShell area="customer" active="requests"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Customer account</p><h1 className="mt-1 text-3xl font-bold">Welcome{profile?.full_name ? `, ${profile.full_name.split(" ")[0]}` : ""}</h1></div><Button asChild variant="gold"><Link to="/request-quote">Request a quote <ArrowRight /></Link></Button></div>
    {data.isLoading ? <p>Loading your records…</p> : data.isError ? <p className="text-destructive">Your records could not be loaded. Please refresh the page.</p> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Active requests" value={requests.filter((r) => !["CLOSED", "CANCELLED"].includes(r.status)).length} icon={ClipboardList} /><Stat label="Pending quotes" value={quotes.filter((q) => q.status === "SENT").length} icon={FileText} tone="gold" /><Stat label="Active jobs" value={jobs.filter((j) => !["COMPLETED", "CLOSED", "CANCELLED"].includes(j.status)).length} icon={BriefcaseBusiness} /><Stat label="Outstanding balance" value={money(invoices.reduce((sum, i) => sum + (i.status === "PAID" ? 0 : Math.max(0, Number(i.total) - Number(i.amount_paid))), 0))} icon={Receipt} tone="gold" /><Stat label="Completed jobs" value={jobs.filter((j) => ["COMPLETED", "CLOSED"].includes(j.status)).length} icon={BriefcaseBusiness} tone="whatsapp" /></div>
    <div className="mt-8 grid gap-x-8 lg:grid-cols-2"><Panel id="requests" title="My Requests">{list(requests, "No requests yet.")}</Panel><Panel id="visits" title="My Site Visits">{list(visits, "No site visits scheduled.")}</Panel><Panel id="quotations" title="My Quotations">{list(quotes, "No quotations issued yet.")}</Panel><Panel id="jobs" title="My Jobs">{list(jobs, "No jobs yet.")}</Panel><Panel id="invoices" title="My Invoices">{invoices.length ? <div className="space-y-2">{invoices.map((i) => <div key={i.id} className="flex justify-between rounded-md border border-border bg-card p-4 text-sm"><span>{i.reference} · {i.status}</span><strong>{money(i.total)}</strong></div>)}</div> : <Empty text="No invoices yet." />}</Panel><Panel id="payments" title="My Payments">{payments.length ? <div className="space-y-2">{payments.map((p) => <div key={p.id} className="flex justify-between rounded-md border border-border bg-card p-4 text-sm"><span>{p.reference} · {p.status}</span><strong>{money(p.amount)}</strong></div>)}</div> : <Empty text="No payments recorded." />}</Panel><Panel id="receipts" title="My Receipts">{receipts.length ? <div className="space-y-2">{receipts.map((r) => <div key={r.id} className="flex justify-between rounded-md border border-border bg-card p-4 text-sm"><span>{r.reference}</span><strong>{money(r.amount)}</strong></div>)}</div> : <Empty text="No receipts yet." />}</Panel><Panel id="documents" title="My Documents">{documents.length ? <div className="space-y-2">{documents.map((d) => <div key={d.id} className="flex justify-between rounded-md border border-border bg-card p-4 text-sm"><span>{d.title} · {d.doc_type}</span><span className="text-muted-foreground">{day(d.created_at)}</span></div>)}</div> : <Empty text="No documents shared yet." />}</Panel><Panel id="reviews" title="My Reviews">{reviews.length ? <p className="text-sm">{reviews.length} review{reviews.length === 1 ? "" : "s"} submitted</p> : <Empty text="No reviews submitted yet." />}<Button asChild variant="outline" className="mt-3"><Link to="/reviews">Leave a review</Link></Button></Panel><Panel id="profile" title="Profile"><p className="text-sm text-muted-foreground">{profile?.full_name ?? "Your account"} · {profile?.email ?? access.data?.user?.email}</p></Panel></div></>}
  </DashboardShell>;
}
