/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/request-quote': typeof RequestQuoteRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/request-quote': typeof RequestQuoteRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/request-quote': typeof RequestQuoteRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/request-quote'
    | '/reviews'
    | '/terms'
    | '/projects/$slug'
    | '/services/$slug'
    | '/projects/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/request-quote'
    | '/reviews'
    | '/terms'
    | '/projects/$slug'
    | '/services/$slug'
    | '/projects'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/request-quote'
    | '/reviews'
    | '/terms'
    | '/projects/$slug'
    | '/services/$slug'
    | '/projects/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  ReviewsRoute: typeof ReviewsRoute
  TermsRoute: typeof TermsRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  ReviewsRoute: ReviewsRoute,
  TermsRoute: TermsRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
